version: '3.8'

services:
  backend:
    build:
      context: ./PentaSecurtiy_BE
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

  frontend:
    build:
      context: ./PentaSecurtiy_FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
